Repository Pre-Onboarding-FE-Team07/wanted-codestates-project-7-11, pull requests merged in 2022-03, with the labels that each got.

#4 Feature/2/chart doughnut
  package-lock.json
  package.json
  src/components/ChartDoughnut.vue
  src/datas/enterprise.json
  src/datas/user.json
  src/scss/chartDoughnut.scss
  src/scss/main.scss
Labels: enhancement

#9 Feature: Pentagon Chart 구현
  src/components/ChartPentagon.vue
  static/radar_cat.png
Labels: enhancement

#12 Feature: UI 컴포넌트 연결
  src/App.vue
  src/components/ChartBar.vue
  src/components/ChartBarView.vue
  src/components/ChartDoughnut.vue
  src/components/ChartPentagon.vue
  src/components/HeaderBar.vue
  src/components/SearchBar.vue
  src/components/TabsSelect.vue
Labels: enhancement

#19 Docs: README.md 작성
  README.md
Labels: documentation

#18 Feat: Bar Chart랑 Tab 연결
  src/App.vue
  src/components/ChartBar.vue
  src/components/ChartBarView.vue
Labels: enhancement

#17 Feat: Pentagon Chart에 기업 검색결과 연결
  src/components/ChartPentagon.vue
Labels: enhancement

#22 Feat: Pentagon Chart 탭 & 리셋 연동
  src/App.vue
  src/components/ChartPentagon.vue
Labels: bug, enhancement
